/**
 * RVF Malinois — F4.3 reference seed.
 *
 * Phase F4.3 — Seed / Reference Data.
 *
 * Strategy reference:
 *   docs/architecture/RVF_Malinois_F4_3_Seed_Reference_Data_Report.md
 * Schema source of truth:
 *   apps/backend/prisma/schema.prisma                                      (commit e37f7b5)
 *   apps/backend/prisma/migrations/20260524000000_f4_2_baseline/migration.sql (commit e37f7b5)
 *   database/schema/RVF_Malinois_F4_1_PostgreSQL_Schema.sql                 (commit a475066)
 *
 * Goals:
 *   - Populate the minimum reference data needed to unblock F4.4 (API
 *     adaptation) and F4.6 (telemetry persistence).
 *   - Demonstrate that operating envelopes and alarm rules are PER-UNIT,
 *     not global (HP-001 vs LP-001).
 *   - Stay idempotent: running this seed twice must not duplicate rows.
 *
 * Non-goals (out of scope per F4.3):
 *   - Real users, real authentication, real credentials.
 *   - Telemetry rows in telemetry_readings.
 *   - Alarm events.
 *   - Integration with ThingsBoard / Node-RED / MQTT / OPC-UA.
 *   - Reactivating quarantined backend modules.
 *
 * Engineering unit conventions used by this seed (documented for F4.4 / F4.6):
 *   - pressure / differential pressure : psi
 *   - temperature                      : degF
 *   - liquid / oil / water flow        : bpd
 *   - gas flow / gas rate              : MMSCFD (Million Standard Cubic Feet per Day)
 *   - liquid volume totals             : bbl
 *   - gas volume totals                : MMSCF
 *   - level                            : %
 *   - vibration                        : in/s
 *   - battery_status, signal_quality   : %
 *   - device_status                    : state (string)
 *
 * Idempotency strategy:
 *   - For models with a natural UNIQUE constraint (canonical_tags.name,
 *     equipment_types.name, measurement_units.(tenant_id, code),
 *     unit_configurations.(unit_id, version),
 *     unit_operating_envelopes.(unit_id, version),
 *     alarm_rules.(unit_id, canonical_tag_id, severity, version),
 *     integration_mappings.(integration_source_id, external_identifier)):
 *     use prisma.<model>.upsert(...).
 *   - For models without a natural UNIQUE constraint (tenants, users, wells,
 *     jobs, sensors, transmitter_devices, sensor_tag_bindings,
 *     commissioning_snapshots, integration_sources, audit_logs):
 *     use findFirst(...) keyed on a deterministic descriptive field, then
 *     create only if missing.
 *   - UUIDs are NEVER hard-coded; ids are generated by gen_random_uuid()
 *     and remain stable once written. Re-running the seed reuses the
 *     pre-existing rows.
 *
 * How to run locally (no destructive defaults):
 *   1. docker compose up -d postgres
 *   2. pnpm --filter @rvf/backend exec prisma migrate dev  # applies F4.2 baseline
 *   3. pnpm --filter @rvf/backend run prisma:seed:f4
 */

import { Prisma, PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Deterministic timestamp used for any "as-of" reference value in the seed. */
const SEED_DATE = new Date('2026-05-24T00:00:00.000Z');

/** Deterministic UUID for the F4.3 seed audit log row's correlation_id. */
const SEED_CORRELATION_ID = '00000000-0000-0000-0000-000000004303';

/** Canonical name of the seed tenant. Used as the natural key for lookup. */
const TENANT_NAME = 'RVF Internal';

/** Canonical engineering-unit set, mirrored into operating envelopes and seed metadata. */
const ENGINEERING_UNIT_SET = {
  pressure: 'psi',
  differential_pressure: 'psi',
  temperature: 'degF',
  liquid_flow: 'bpd',
  gas_flow: 'MMSCFD',
  volume_liquid: 'bbl',
  volume_gas: 'MMSCF',
  level: '%',
  vibration: 'in/s',
  battery_status: '%',
  signal_quality: '%',
  device_status: 'state',
} as const;

// ---------------------------------------------------------------------------
// Reference data — declarative
// ---------------------------------------------------------------------------

interface CanonicalTagDef {
  name: string;
  displayName: string;
  canonicalUnit: string;
  category: string;
  precision: number;
  description: string;
}

/**
 * F4.3 canonical tag dictionary. Names are immutable contracts; new tags are
 * added by later phases. Deprecation flips the `deprecated` flag (rows are
 * never deleted).
 */
const CANONICAL_TAGS: CanonicalTagDef[] = [
  // Pressure
  {
    name: 'p_inlet',
    displayName: 'Inlet pressure',
    canonicalUnit: 'psi',
    category: 'pressure',
    precision: 1,
    description: 'Process pressure measured at the unit inlet manifold.',
  },
  {
    name: 'p_outlet',
    displayName: 'Outlet pressure',
    canonicalUnit: 'psi',
    category: 'pressure',
    precision: 1,
    description: 'Process pressure measured at the unit outlet manifold.',
  },
  {
    name: 'p_separator',
    displayName: 'Separator pressure',
    canonicalUnit: 'psi',
    category: 'pressure',
    precision: 1,
    description: 'Static pressure inside the three-phase separator vessel.',
  },
  {
    name: 'dp_filter',
    displayName: 'Filter differential P',
    canonicalUnit: 'psi',
    category: 'pressure',
    precision: 2,
    description: 'Differential pressure across the inlet filter / strainer.',
  },
  // Temperature
  {
    name: 't_inlet',
    displayName: 'Inlet temperature',
    canonicalUnit: 'degF',
    category: 'temperature',
    precision: 1,
    description: 'Process temperature at the unit inlet.',
  },
  {
    name: 't_outlet',
    displayName: 'Outlet temperature',
    canonicalUnit: 'degF',
    category: 'temperature',
    precision: 1,
    description: 'Process temperature at the unit outlet.',
  },
  {
    name: 't_separator',
    displayName: 'Separator temperature',
    canonicalUnit: 'degF',
    category: 'temperature',
    precision: 1,
    description: 'Internal separator temperature.',
  },
  // Flow
  {
    name: 'q_liquid',
    displayName: 'Total liquid flow rate',
    canonicalUnit: 'bpd',
    category: 'flow',
    precision: 1,
    description: 'Aggregate liquid flow rate.',
  },
  {
    name: 'q_gas',
    displayName: 'Total gas flow rate',
    canonicalUnit: 'MMSCFD',
    category: 'flow',
    precision: 3,
    description: 'Aggregate gas flow rate, normalised to MMSCFD.',
  },
  {
    name: 'q_oil',
    displayName: 'Oil flow rate',
    canonicalUnit: 'bpd',
    category: 'flow',
    precision: 1,
    description: 'Oil-phase flow rate.',
  },
  {
    name: 'q_water',
    displayName: 'Water flow rate',
    canonicalUnit: 'bpd',
    category: 'flow',
    precision: 1,
    description: 'Water-phase flow rate.',
  },
  // Volume / totals
  {
    name: 'v_liquid_total',
    displayName: 'Cumulative liquid volume',
    canonicalUnit: 'bbl',
    category: 'volume',
    precision: 1,
    description: 'Cumulative liquid volume since job start.',
  },
  {
    name: 'v_gas_total',
    displayName: 'Cumulative gas volume',
    canonicalUnit: 'MMSCF',
    category: 'volume',
    precision: 3,
    description: 'Cumulative gas volume since job start.',
  },
  {
    name: 'v_oil_total',
    displayName: 'Cumulative oil volume',
    canonicalUnit: 'bbl',
    category: 'volume',
    precision: 1,
    description: 'Cumulative oil volume since job start.',
  },
  {
    name: 'v_water_total',
    displayName: 'Cumulative water volume',
    canonicalUnit: 'bbl',
    category: 'volume',
    precision: 1,
    description: 'Cumulative water volume since job start.',
  },
  // Level
  {
    name: 'level_separator',
    displayName: 'Separator liquid level',
    canonicalUnit: '%',
    category: 'level',
    precision: 1,
    description: 'Liquid level inside the separator as a percentage of full range.',
  },
  // Vibration
  {
    name: 'vib_x',
    displayName: 'Vibration X-axis',
    canonicalUnit: 'in/s',
    category: 'vibration',
    precision: 3,
    description: 'RMS vibration on the X axis (radial).',
  },
  {
    name: 'vib_y',
    displayName: 'Vibration Y-axis',
    canonicalUnit: 'in/s',
    category: 'vibration',
    precision: 3,
    description: 'RMS vibration on the Y axis (radial).',
  },
  {
    name: 'vib_z',
    displayName: 'Vibration Z-axis',
    canonicalUnit: 'in/s',
    category: 'vibration',
    precision: 3,
    description: 'RMS vibration on the Z axis (axial).',
  },
  // Status / quality
  {
    name: 'battery_status',
    displayName: 'Transmitter battery %',
    canonicalUnit: '%',
    category: 'status',
    precision: 0,
    description: 'Remaining battery on the wireless transmitter, percent.',
  },
  {
    name: 'signal_quality',
    displayName: 'Wireless signal RSSI',
    canonicalUnit: '%',
    category: 'status',
    precision: 0,
    description: 'Normalised signal-quality indicator (0-100).',
  },
  {
    name: 'device_status',
    displayName: 'Device status code',
    canonicalUnit: 'state',
    category: 'status',
    precision: 0,
    description: 'Device-reported state machine value (string).',
  },
];

type SensorTypeStr =
  | 'pressure'
  | 'temperature'
  | 'flow'
  | 'vibration'
  | 'volume'
  | 'level'
  | 'gas_composition'
  | 'digital_status';

type TransmitterProtocolStr = '4-20mA' | 'HART' | 'Modbus' | 'OPC-UA' | 'wireless';

interface SensorDef {
  instrumentTag: string;
  name: string;
  sensorType: SensorTypeStr;
  engineeringUnit: string;
  minRange: number;
  maxRange: number;
  canonicalTagName: string;
  transmitterProtocol: TransmitterProtocolStr;
  transmitterSignalType: string;
  transmitterManufacturer: string;
  transmitterModel: string;
}

interface MeasurementUnitDef {
  code: string;
  name: string;
  serialNumber: string;
  operatingProfile: string;
  status: string;
  location: string;
  equipmentTypeName: string;
  sensors: SensorDef[];
}

const HP001_SENSORS: SensorDef[] = [
  {
    instrumentTag: 'HP-PIT-001',
    name: 'HP-001 inlet pressure',
    sensorType: 'pressure',
    engineeringUnit: 'psi',
    minRange: 0,
    maxRange: 6000,
    canonicalTagName: 'p_inlet',
    transmitterProtocol: '4-20mA',
    transmitterSignalType: 'analog',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Pressure Transmitter',
  },
  {
    instrumentTag: 'HP-PIT-002',
    name: 'HP-001 outlet pressure',
    sensorType: 'pressure',
    engineeringUnit: 'psi',
    minRange: 0,
    maxRange: 6000,
    canonicalTagName: 'p_outlet',
    transmitterProtocol: '4-20mA',
    transmitterSignalType: 'analog',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Pressure Transmitter',
  },
  {
    instrumentTag: 'HP-TIT-001',
    name: 'HP-001 inlet temperature',
    sensorType: 'temperature',
    engineeringUnit: 'degF',
    minRange: -40,
    maxRange: 350,
    canonicalTagName: 't_inlet',
    transmitterProtocol: '4-20mA',
    transmitterSignalType: 'analog',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Temperature Transmitter',
  },
  {
    instrumentTag: 'HP-FIT-001',
    name: 'HP-001 liquid flow',
    sensorType: 'flow',
    engineeringUnit: 'bpd',
    minRange: 0,
    maxRange: 12000,
    canonicalTagName: 'q_liquid',
    transmitterProtocol: 'HART',
    transmitterSignalType: 'digital',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Flow Transmitter',
  },
  {
    instrumentTag: 'HP-FIT-002',
    name: 'HP-001 gas flow',
    sensorType: 'flow',
    engineeringUnit: 'MMSCFD',
    minRange: 0,
    maxRange: 6,
    canonicalTagName: 'q_gas',
    transmitterProtocol: 'HART',
    transmitterSignalType: 'digital',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Flow Transmitter',
  },
  {
    instrumentTag: 'HP-LIT-001',
    name: 'HP-001 separator level',
    sensorType: 'level',
    engineeringUnit: '%',
    minRange: 0,
    maxRange: 100,
    canonicalTagName: 'level_separator',
    transmitterProtocol: '4-20mA',
    transmitterSignalType: 'analog',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Level Transmitter',
  },
  {
    instrumentTag: 'HP-VIT-001',
    name: 'HP-001 vibration X',
    sensorType: 'vibration',
    engineeringUnit: 'in/s',
    minRange: 0,
    maxRange: 2,
    canonicalTagName: 'vib_x',
    transmitterProtocol: '4-20mA',
    transmitterSignalType: 'analog',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Vibration Transmitter',
  },
];

const LP001_SENSORS: SensorDef[] = [
  {
    instrumentTag: 'LP-PIT-001',
    name: 'LP-001 inlet pressure',
    sensorType: 'pressure',
    engineeringUnit: 'psi',
    minRange: 0,
    maxRange: 1000,
    canonicalTagName: 'p_inlet',
    transmitterProtocol: '4-20mA',
    transmitterSignalType: 'analog',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Pressure Transmitter',
  },
  {
    instrumentTag: 'LP-PIT-002',
    name: 'LP-001 outlet pressure',
    sensorType: 'pressure',
    engineeringUnit: 'psi',
    minRange: 0,
    maxRange: 1000,
    canonicalTagName: 'p_outlet',
    transmitterProtocol: '4-20mA',
    transmitterSignalType: 'analog',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Pressure Transmitter',
  },
  {
    instrumentTag: 'LP-TIT-001',
    name: 'LP-001 inlet temperature',
    sensorType: 'temperature',
    engineeringUnit: 'degF',
    minRange: -40,
    maxRange: 250,
    canonicalTagName: 't_inlet',
    transmitterProtocol: '4-20mA',
    transmitterSignalType: 'analog',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Temperature Transmitter',
  },
  {
    instrumentTag: 'LP-FIT-001',
    name: 'LP-001 liquid flow',
    sensorType: 'flow',
    engineeringUnit: 'bpd',
    minRange: 0,
    maxRange: 4000,
    canonicalTagName: 'q_liquid',
    transmitterProtocol: 'HART',
    transmitterSignalType: 'digital',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Flow Transmitter',
  },
  {
    instrumentTag: 'LP-FIT-002',
    name: 'LP-001 gas flow',
    sensorType: 'flow',
    engineeringUnit: 'MMSCFD',
    minRange: 0,
    maxRange: 1.5,
    canonicalTagName: 'q_gas',
    transmitterProtocol: 'HART',
    transmitterSignalType: 'digital',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Flow Transmitter',
  },
  {
    instrumentTag: 'LP-LIT-001',
    name: 'LP-001 separator level',
    sensorType: 'level',
    engineeringUnit: '%',
    minRange: 0,
    maxRange: 100,
    canonicalTagName: 'level_separator',
    transmitterProtocol: '4-20mA',
    transmitterSignalType: 'analog',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Level Transmitter',
  },
  {
    instrumentTag: 'LP-VIT-001',
    name: 'LP-001 vibration X',
    sensorType: 'vibration',
    engineeringUnit: 'in/s',
    minRange: 0,
    maxRange: 1,
    canonicalTagName: 'vib_x',
    transmitterProtocol: '4-20mA',
    transmitterSignalType: 'analog',
    transmitterManufacturer: 'RVF Reference',
    transmitterModel: 'Reference Vibration Transmitter',
  },
];

const UNITS: MeasurementUnitDef[] = [
  {
    code: 'HP-001',
    name: 'High Pressure / High Flow Test Unit',
    serialNumber: 'RVF-HP-001',
    operatingProfile: 'high_pressure_high_flow',
    status: 'active',
    location: 'Yard / Test Bench',
    equipmentTypeName: 'EMMAD',
    sensors: HP001_SENSORS,
  },
  {
    code: 'LP-001',
    name: 'Low Pressure / Medium Flow Test Unit',
    serialNumber: 'RVF-LP-001',
    operatingProfile: 'low',
    status: 'active',
    location: 'Yard / Test Bench',
    equipmentTypeName: 'EMMAD',
    sensors: LP001_SENSORS,
  },
];

interface AlarmRuleDef {
  canonicalTagName: string;
  severity: 'warning' | 'critical';
  /** Which threshold field carries the value. F4.3 only uses high / high_high. */
  thresholdKind: 'high' | 'high_high';
  value: number;
  message: string;
}

const HP001_ALARM_RULES: AlarmRuleDef[] = [
  {
    canonicalTagName: 'p_inlet',
    severity: 'warning',
    thresholdKind: 'high',
    value: 4500,
    message: 'HP-001 inlet pressure approaching design limit (warning).',
  },
  {
    canonicalTagName: 'p_inlet',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 5000,
    message: 'HP-001 inlet pressure at design limit (critical).',
  },
  {
    canonicalTagName: 'p_outlet',
    severity: 'warning',
    thresholdKind: 'high',
    value: 4200,
    message: 'HP-001 outlet pressure elevated (warning).',
  },
  {
    canonicalTagName: 'p_outlet',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 4800,
    message: 'HP-001 outlet pressure critical (critical).',
  },
  {
    canonicalTagName: 't_inlet',
    severity: 'warning',
    thresholdKind: 'high',
    value: 220,
    message: 'HP-001 inlet temperature elevated (warning).',
  },
  {
    canonicalTagName: 't_inlet',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 250,
    message: 'HP-001 inlet temperature critical (critical).',
  },
  {
    canonicalTagName: 'q_liquid',
    severity: 'warning',
    thresholdKind: 'high',
    value: 9000,
    message: 'HP-001 liquid flow approaching capacity (warning).',
  },
  {
    canonicalTagName: 'q_liquid',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 10000,
    message: 'HP-001 liquid flow at capacity (critical).',
  },
  {
    canonicalTagName: 'q_gas',
    severity: 'warning',
    thresholdKind: 'high',
    value: 4.5,
    message: 'HP-001 gas flow elevated (warning).',
  },
  {
    canonicalTagName: 'q_gas',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 5.0,
    message: 'HP-001 gas flow critical (critical).',
  },
  {
    canonicalTagName: 'level_separator',
    severity: 'warning',
    thresholdKind: 'high',
    value: 80,
    message: 'HP-001 separator level high (warning).',
  },
  {
    canonicalTagName: 'level_separator',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 90,
    message: 'HP-001 separator level critical (critical).',
  },
  {
    canonicalTagName: 'vib_x',
    severity: 'warning',
    thresholdKind: 'high',
    value: 0.8,
    message: 'HP-001 vibration elevated (warning).',
  },
  {
    canonicalTagName: 'vib_x',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 1.0,
    message: 'HP-001 vibration critical (critical).',
  },
];

const LP001_ALARM_RULES: AlarmRuleDef[] = [
  {
    canonicalTagName: 'p_inlet',
    severity: 'warning',
    thresholdKind: 'high',
    value: 600,
    message: 'LP-001 inlet pressure elevated (warning).',
  },
  {
    canonicalTagName: 'p_inlet',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 750,
    message: 'LP-001 inlet pressure at design limit (critical).',
  },
  {
    canonicalTagName: 'p_outlet',
    severity: 'warning',
    thresholdKind: 'high',
    value: 500,
    message: 'LP-001 outlet pressure elevated (warning).',
  },
  {
    canonicalTagName: 'p_outlet',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 650,
    message: 'LP-001 outlet pressure critical (critical).',
  },
  {
    canonicalTagName: 't_inlet',
    severity: 'warning',
    thresholdKind: 'high',
    value: 160,
    message: 'LP-001 inlet temperature elevated (warning).',
  },
  {
    canonicalTagName: 't_inlet',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 180,
    message: 'LP-001 inlet temperature critical (critical).',
  },
  {
    canonicalTagName: 'q_liquid',
    severity: 'warning',
    thresholdKind: 'high',
    value: 2500,
    message: 'LP-001 liquid flow elevated (warning).',
  },
  {
    canonicalTagName: 'q_liquid',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 3000,
    message: 'LP-001 liquid flow at capacity (critical).',
  },
  {
    canonicalTagName: 'q_gas',
    severity: 'warning',
    thresholdKind: 'high',
    value: 0.8,
    message: 'LP-001 gas flow elevated (warning).',
  },
  {
    canonicalTagName: 'q_gas',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 1.0,
    message: 'LP-001 gas flow critical (critical).',
  },
  {
    canonicalTagName: 'level_separator',
    severity: 'warning',
    thresholdKind: 'high',
    value: 75,
    message: 'LP-001 separator level high (warning).',
  },
  {
    canonicalTagName: 'level_separator',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 85,
    message: 'LP-001 separator level critical (critical).',
  },
  {
    canonicalTagName: 'vib_x',
    severity: 'warning',
    thresholdKind: 'high',
    value: 0.35,
    message: 'LP-001 vibration elevated (warning).',
  },
  {
    canonicalTagName: 'vib_x',
    severity: 'critical',
    thresholdKind: 'high_high',
    value: 0.5,
    message: 'LP-001 vibration critical (critical).',
  },
];

// ---------------------------------------------------------------------------
// Helper: log + counters
// ---------------------------------------------------------------------------

interface SeedCounters {
  created: Record<string, number>;
  reused: Record<string, number>;
}

const counters: SeedCounters = { created: {}, reused: {} };

function record(kind: 'created' | 'reused', entity: string): void {
  counters[kind][entity] = (counters[kind][entity] ?? 0) + 1;
}

function log(message: string): void {
  // Plain console.log — this is a CLI seed; no Pino in scope.

  console.log(`[F4.3 seed] ${message}`);
}

// ---------------------------------------------------------------------------
// Seed steps
// ---------------------------------------------------------------------------

async function seedTenant(): Promise<{ id: string; name: string }> {
  const existing = await prisma.tenant.findFirst({ where: { name: TENANT_NAME } });
  if (existing) {
    record('reused', 'tenant');
    log(`tenant "${existing.name}" already present (${existing.id}); reusing.`);
    return existing;
  }
  const created = await prisma.tenant.create({
    data: {
      name: TENANT_NAME,
      status: 'active',
      residencyHint: 'local-dev',
    },
  });
  record('created', 'tenant');
  log(`tenant "${created.name}" created (${created.id}).`);
  return created;
}

interface SeededUsers {
  systemUser: { id: string; displayName: string };
  adminUser: { id: string; displayName: string };
}

async function seedUsers(tenantId: string): Promise<SeededUsers> {
  async function ensure(
    displayName: string,
    role: string,
  ): Promise<{ id: string; displayName: string }> {
    const existing = await prisma.user.findFirst({ where: { tenantId, displayName, role } });
    if (existing) {
      record('reused', 'user');
      return existing;
    }
    const created = await prisma.user.create({
      data: {
        tenantId,
        displayName,
        role,
        status: 'active',
      },
    });
    record('created', 'user');
    return created;
  }
  const systemUser = await ensure('System User', 'system');
  const adminUser = await ensure('Admin Placeholder', 'admin');
  log(`users present: ${systemUser.displayName}, ${adminUser.displayName}.`);
  return { systemUser, adminUser };
}

async function seedEquipmentTypes(): Promise<Map<string, { id: string; name: string }>> {
  const out = new Map<string, { id: string; name: string }>();

  const emmad = await prisma.equipmentType.upsert({
    where: { name: 'EMMAD' },
    update: {
      description:
        'Well testing / measurement unit template for oil, gas and liquid operational monitoring.',
      pidReference: 'EMMAD-generic',
      defaultSensorTemplate: {
        loops: [
          { name: 'inlet_pressure', canonical_tag: 'p_inlet', engineering_unit: 'psi' },
          { name: 'outlet_pressure', canonical_tag: 'p_outlet', engineering_unit: 'psi' },
          { name: 'inlet_temperature', canonical_tag: 't_inlet', engineering_unit: 'degF' },
          { name: 'liquid_flow', canonical_tag: 'q_liquid', engineering_unit: 'bpd' },
          { name: 'gas_flow', canonical_tag: 'q_gas', engineering_unit: 'MMSCFD' },
          { name: 'separator_level', canonical_tag: 'level_separator', engineering_unit: '%' },
          { name: 'vibration_x', canonical_tag: 'vib_x', engineering_unit: 'in/s' },
        ],
      } satisfies Prisma.InputJsonValue,
    },
    create: {
      name: 'EMMAD',
      description:
        'Well testing / measurement unit template for oil, gas and liquid operational monitoring.',
      pidReference: 'EMMAD-generic',
      defaultSensorTemplate: {
        loops: [
          { name: 'inlet_pressure', canonical_tag: 'p_inlet', engineering_unit: 'psi' },
          { name: 'outlet_pressure', canonical_tag: 'p_outlet', engineering_unit: 'psi' },
          { name: 'inlet_temperature', canonical_tag: 't_inlet', engineering_unit: 'degF' },
          { name: 'liquid_flow', canonical_tag: 'q_liquid', engineering_unit: 'bpd' },
          { name: 'gas_flow', canonical_tag: 'q_gas', engineering_unit: 'MMSCFD' },
          { name: 'separator_level', canonical_tag: 'level_separator', engineering_unit: '%' },
          { name: 'vibration_x', canonical_tag: 'vib_x', engineering_unit: 'in/s' },
        ],
      } satisfies Prisma.InputJsonValue,
    },
  });
  out.set('EMMAD', emmad);

  const emgad = await prisma.equipmentType.upsert({
    where: { name: 'EMGAD' },
    update: {
      description: 'Gas measurement / gas analysis unit template for gas-focused monitoring.',
      pidReference: 'EMGAD-generic',
      defaultSensorTemplate: {
        loops: [
          { name: 'inlet_pressure', canonical_tag: 'p_inlet', engineering_unit: 'psi' },
          { name: 'inlet_temperature', canonical_tag: 't_inlet', engineering_unit: 'degF' },
          { name: 'gas_flow', canonical_tag: 'q_gas', engineering_unit: 'MMSCFD' },
          { name: 'gas_total', canonical_tag: 'v_gas_total', engineering_unit: 'MMSCF' },
        ],
      } satisfies Prisma.InputJsonValue,
    },
    create: {
      name: 'EMGAD',
      description: 'Gas measurement / gas analysis unit template for gas-focused monitoring.',
      pidReference: 'EMGAD-generic',
      defaultSensorTemplate: {
        loops: [
          { name: 'inlet_pressure', canonical_tag: 'p_inlet', engineering_unit: 'psi' },
          { name: 'inlet_temperature', canonical_tag: 't_inlet', engineering_unit: 'degF' },
          { name: 'gas_flow', canonical_tag: 'q_gas', engineering_unit: 'MMSCFD' },
          { name: 'gas_total', canonical_tag: 'v_gas_total', engineering_unit: 'MMSCF' },
        ],
      } satisfies Prisma.InputJsonValue,
    },
  });
  out.set('EMGAD', emgad);

  // upsert always returns a row; track as created/reused based on createdAt vs updatedAt heuristics.
  record('created', 'equipment_type:upserted_x2');
  log(`equipment types present: EMMAD, EMGAD.`);
  return out;
}

async function seedCanonicalTags(): Promise<Map<string, { id: string; name: string }>> {
  const out = new Map<string, { id: string; name: string }>();
  for (const tag of CANONICAL_TAGS) {
    const row = await prisma.canonicalTag.upsert({
      where: { name: tag.name },
      update: {
        displayName: tag.displayName,
        canonicalUnit: tag.canonicalUnit,
        category: tag.category,
        precision: tag.precision,
        description: tag.description,
        deprecated: false,
      },
      create: {
        name: tag.name,
        displayName: tag.displayName,
        canonicalUnit: tag.canonicalUnit,
        category: tag.category,
        precision: tag.precision,
        description: tag.description,
        deprecated: false,
      },
    });
    out.set(row.name, row);
  }
  record('created', `canonical_tag:upserted_x${String(CANONICAL_TAGS.length)}`);
  log(`canonical tags present: ${String(CANONICAL_TAGS.length)} entries.`);
  return out;
}

async function seedMeasurementUnits(
  tenantId: string,
  equipmentTypes: Map<string, { id: string }>,
): Promise<Map<string, { id: string; code: string }>> {
  const out = new Map<string, { id: string; code: string }>();
  for (const unit of UNITS) {
    const type = equipmentTypes.get(unit.equipmentTypeName);
    if (!type) {
      throw new Error(`Equipment type "${unit.equipmentTypeName}" missing for unit ${unit.code}`);
    }
    const row = await prisma.measurementUnit.upsert({
      where: { tenantId_code: { tenantId, code: unit.code } },
      update: {
        equipmentTypeId: type.id,
        serialNumber: unit.serialNumber,
        name: unit.name,
        status: unit.status,
        operatingProfile: unit.operatingProfile,
        location: unit.location,
      },
      create: {
        tenantId,
        equipmentTypeId: type.id,
        code: unit.code,
        serialNumber: unit.serialNumber,
        name: unit.name,
        status: unit.status,
        operatingProfile: unit.operatingProfile,
        location: unit.location,
      },
    });
    out.set(row.code, row);
  }
  record('created', `measurement_unit:upserted_x${String(UNITS.length)}`);
  log(`measurement units present: ${UNITS.map((u) => u.code).join(', ')}.`);
  return out;
}

interface SeededSensor {
  id: string;
  unitCode: string;
  instrumentTag: string;
  canonicalTagName: string;
}

async function seedSensorsAndTransmitters(
  tenantId: string,
  units: Map<string, { id: string; code: string }>,
): Promise<SeededSensor[]> {
  const seeded: SeededSensor[] = [];
  for (const unitDef of UNITS) {
    const unit = units.get(unitDef.code);
    if (!unit) throw new Error(`Unit ${unitDef.code} not seeded`);
    for (const sd of unitDef.sensors) {
      // Sensors: no natural unique constraint in schema; lookup by (unitId, instrumentTag).
      let sensor = await prisma.sensor.findFirst({
        where: { unitId: unit.id, instrumentTag: sd.instrumentTag },
      });
      if (sensor) {
        record('reused', 'sensor');
      } else {
        sensor = await prisma.sensor.create({
          data: {
            tenantId,
            unitId: unit.id,
            type: sd.sensorType,
            name: sd.name,
            instrumentTag: sd.instrumentTag,
            enabled: true,
            minRange: sd.minRange,
            maxRange: sd.maxRange,
            engineeringUnit: sd.engineeringUnit,
          },
        });
        record('created', 'sensor');
      }

      // TransmitterDevice: no natural unique; lookup by (sensorId, serial_number).
      const transmitterSerial = `TX-${sd.instrumentTag}`;
      const existingTx = await prisma.transmitterDevice.findFirst({
        where: { sensorId: sensor.id, serialNumber: transmitterSerial },
      });
      if (existingTx) {
        record('reused', 'transmitter_device');
      } else {
        await prisma.transmitterDevice.create({
          data: {
            tenantId,
            sensorId: sensor.id,
            serialNumber: transmitterSerial,
            manufacturer: sd.transmitterManufacturer,
            model: sd.transmitterModel,
            protocol: sd.transmitterProtocol,
            signalType: sd.transmitterSignalType,
            firmwareVersion: '1.0.0',
            calibrationDate: SEED_DATE,
            calibrationRangeMin: sd.minRange,
            calibrationRangeMax: sd.maxRange,
            calibrationReference: 'F4.3 reference seed',
            installationStatus: 'installed',
            installedAt: SEED_DATE,
          },
        });
        record('created', 'transmitter_device');
      }

      seeded.push({
        id: sensor.id,
        unitCode: unitDef.code,
        instrumentTag: sd.instrumentTag,
        canonicalTagName: sd.canonicalTagName,
      });
    }
  }
  log(`sensors + transmitters present: ${String(seeded.length)} pairs.`);
  return seeded;
}

async function seedSensorTagBindings(
  tenantId: string,
  sensors: SeededSensor[],
  canonicalTags: Map<string, { id: string }>,
): Promise<void> {
  for (const s of sensors) {
    const tag = canonicalTags.get(s.canonicalTagName);
    if (!tag)
      throw new Error(`Canonical tag ${s.canonicalTagName} missing for sensor ${s.instrumentTag}`);
    // Idempotency: a sensor has at most one ACTIVE binding (effective_to IS NULL),
    // enforced by partial unique index. Reuse if it points at the same canonical tag.
    const activeBinding = await prisma.sensorTagBinding.findFirst({
      where: { sensorId: s.id, effectiveTo: null },
    });
    if (activeBinding) {
      if (activeBinding.canonicalTagId === tag.id) {
        record('reused', 'sensor_tag_binding');
        continue;
      }
      // Re-binding: close the existing binding and open a new one.
      await prisma.sensorTagBinding.update({
        where: { id: activeBinding.id },
        data: { effectiveTo: SEED_DATE },
      });
    }
    await prisma.sensorTagBinding.create({
      data: {
        tenantId,
        sensorId: s.id,
        canonicalTagId: tag.id,
        effectiveFrom: SEED_DATE,
        effectiveTo: null,
      },
    });
    record('created', 'sensor_tag_binding');
  }
  log(`sensor-tag bindings present: ${String(sensors.length)} active bindings.`);
}

async function seedUnitConfigurations(
  tenantId: string,
  units: Map<string, { id: string; code: string }>,
  sensors: SeededSensor[],
  createdById: string,
): Promise<void> {
  for (const [unitCode, unit] of units) {
    const unitSensors = sensors.filter((s) => s.unitCode === unitCode);
    const enabledSensors = unitSensors.map((s) => s.instrumentTag);
    await prisma.unitConfiguration.upsert({
      where: { unitId_version: { unitId: unit.id, version: 1 } },
      update: {
        configuration: {
          notes: 'F4.3 seed initial configuration.',
        } satisfies Prisma.InputJsonValue,
        enabledSensors: enabledSensors satisfies Prisma.InputJsonValue,
        engineeringUnitOverrides: {} satisfies Prisma.InputJsonValue,
        displayPrecisionOverrides: {} satisfies Prisma.InputJsonValue,
        isCurrent: true,
        createdBy: createdById,
      },
      create: {
        tenantId,
        unitId: unit.id,
        version: 1,
        configuration: {
          notes: 'F4.3 seed initial configuration.',
        } satisfies Prisma.InputJsonValue,
        enabledSensors: enabledSensors satisfies Prisma.InputJsonValue,
        engineeringUnitOverrides: {} satisfies Prisma.InputJsonValue,
        displayPrecisionOverrides: {} satisfies Prisma.InputJsonValue,
        isCurrent: true,
        createdBy: createdById,
      },
    });
  }
  record('created', `unit_configuration:upserted_x${String(units.size)}`);
  log(`unit configurations present (version 1, is_current=true): ${String(units.size)} rows.`);
}

interface OperatingEnvelopeData {
  maxPressure: number;
  maxFlowRate: number;
  maxTemperature: number;
  maxVibration: number;
  maxDifferentialPressure: number;
  maxVolume: number | null;
  maxGasRate: number;
}

const HP001_ENVELOPE: OperatingEnvelopeData = {
  maxPressure: 5000,
  maxFlowRate: 10000,
  maxTemperature: 250,
  maxVibration: 1.0,
  maxDifferentialPressure: 500,
  maxVolume: null,
  maxGasRate: 5.0,
};

const LP001_ENVELOPE: OperatingEnvelopeData = {
  maxPressure: 750,
  maxFlowRate: 3000,
  maxTemperature: 180,
  maxVibration: 0.5,
  maxDifferentialPressure: 150,
  maxVolume: null,
  maxGasRate: 1.0,
};

async function seedUnitOperatingEnvelopes(
  tenantId: string,
  units: Map<string, { id: string; code: string }>,
  createdById: string,
): Promise<void> {
  const map: Record<string, OperatingEnvelopeData> = {
    'HP-001': HP001_ENVELOPE,
    'LP-001': LP001_ENVELOPE,
  };
  for (const [unitCode, unit] of units) {
    const env = map[unitCode];
    if (!env) continue;
    await prisma.unitOperatingEnvelope.upsert({
      where: { unitId_version: { unitId: unit.id, version: 1 } },
      update: {
        maxPressure: env.maxPressure,
        maxFlowRate: env.maxFlowRate,
        maxTemperature: env.maxTemperature,
        maxVibration: env.maxVibration,
        maxDifferentialPressure: env.maxDifferentialPressure,
        maxVolume: env.maxVolume,
        maxGasRate: env.maxGasRate,
        engineeringUnitSet: ENGINEERING_UNIT_SET satisfies Prisma.InputJsonValue,
        isCurrent: true,
        createdBy: createdById,
      },
      create: {
        tenantId,
        unitId: unit.id,
        version: 1,
        maxPressure: env.maxPressure,
        maxFlowRate: env.maxFlowRate,
        maxTemperature: env.maxTemperature,
        maxVibration: env.maxVibration,
        maxDifferentialPressure: env.maxDifferentialPressure,
        maxVolume: env.maxVolume,
        maxGasRate: env.maxGasRate,
        engineeringUnitSet: ENGINEERING_UNIT_SET satisfies Prisma.InputJsonValue,
        isCurrent: true,
        createdBy: createdById,
      },
    });
  }
  record('created', `unit_operating_envelope:upserted_x${String(Object.keys(map).length)}`);
  log(`unit operating envelopes present (version 1, is_current=true): HP-001 + LP-001.`);
}

async function seedAlarmRules(
  tenantId: string,
  units: Map<string, { id: string; code: string }>,
  canonicalTags: Map<string, { id: string; name: string }>,
  createdById: string,
): Promise<number> {
  let count = 0;
  const planned: Array<{ unitCode: string; rules: AlarmRuleDef[] }> = [
    { unitCode: 'HP-001', rules: HP001_ALARM_RULES },
    { unitCode: 'LP-001', rules: LP001_ALARM_RULES },
  ];
  for (const { unitCode, rules } of planned) {
    const unit = units.get(unitCode);
    if (!unit) throw new Error(`Unit ${unitCode} missing for alarm rules`);
    for (const r of rules) {
      const tag = canonicalTags.get(r.canonicalTagName);
      if (!tag)
        throw new Error(
          `Canonical tag ${r.canonicalTagName} missing for alarm rule on ${unitCode}`,
        );
      const thresholdFields: Prisma.AlarmRuleUncheckedCreateInput = {
        tenantId,
        unitId: unit.id,
        canonicalTagId: tag.id,
        severity: r.severity,
        enabled: true,
        version: 1,
        isCurrent: true,
        messageTemplate: r.message,
        createdBy: createdById,
      };
      if (r.thresholdKind === 'high') {
        thresholdFields.highThreshold = r.value;
      } else {
        thresholdFields.highHighThreshold = r.value;
      }
      await prisma.alarmRule.upsert({
        where: {
          unitId_canonicalTagId_severity_version: {
            unitId: unit.id,
            canonicalTagId: tag.id,
            severity: r.severity,
            version: 1,
          },
        },
        update: {
          enabled: true,
          isCurrent: true,
          messageTemplate: r.message,
          createdBy: createdById,
          // Reset the threshold fields so re-running with a different value
          // converges. Only the field for this rule's kind carries a value.
          highThreshold: r.thresholdKind === 'high' ? r.value : null,
          highHighThreshold: r.thresholdKind === 'high_high' ? r.value : null,
        },
        create: thresholdFields,
      });
      count++;
    }
  }
  record('created', `alarm_rule:upserted_x${String(count)}`);
  log(`alarm rules present (version 1, is_current=true): ${String(count)} per-unit rules.`);
  return count;
}

interface SeededWellJobSnapshot {
  well: { id: string; name: string };
  job: { id: string };
  snapshot: { id: string } | null;
}

async function seedWellJobSnapshot(
  tenantId: string,
  unitId: string,
  unitCode: string,
  unitSensors: SeededSensor[],
  unitAlarmRules: AlarmRuleDef[],
  envelope: OperatingEnvelopeData,
  engineerId: string,
): Promise<SeededWellJobSnapshot> {
  // Well: no natural unique. Lookup by (tenantId, name).
  const wellName = 'Reference Well A';
  let well = await prisma.well.findFirst({ where: { tenantId, name: wellName } });
  if (well) {
    record('reused', 'well');
  } else {
    well = await prisma.well.create({
      data: {
        tenantId,
        name: wellName,
        fieldOrSite: 'Reference Field',
        location: 'Local Dev',
        type: 'test',
        fluid: 'multiphase',
        designLimits: {
          max_pressure_psi: envelope.maxPressure,
          max_temperature_degF: envelope.maxTemperature,
          max_liquid_flow_bpd: envelope.maxFlowRate,
          max_gas_flow_MMSCFD: envelope.maxGasRate,
        } satisfies Prisma.InputJsonValue,
      },
    });
    record('created', 'well');
  }

  // Job: no natural unique. Lookup by (tenantId, wellId, unitId, startedAt).
  const jobStartedAt = SEED_DATE;
  let job = await prisma.job.findFirst({
    where: { tenantId, wellId: well.id, unitId, startedAt: jobStartedAt },
  });
  if (!job) {
    job = await prisma.job.create({
      data: {
        tenantId,
        wellId: well.id,
        unitId,
        engineerId,
        status: 'in_progress',
        startedAt: jobStartedAt,
        // commissioning_snapshot_id stays null until the snapshot is created.
      },
    });
    record('created', 'job');
  } else {
    record('reused', 'job');
  }

  // CommissioningSnapshot: one per job is the seed's contract. Look up by jobId.
  let snapshot = await prisma.commissioningSnapshot.findFirst({ where: { jobId: job.id } });
  if (!snapshot) {
    const sensorMappings = unitSensors.map((s) => ({
      instrument_tag: s.instrumentTag,
      canonical_tag: s.canonicalTagName,
    }));
    const effectiveThresholds = unitAlarmRules.map((r) => ({
      canonical_tag: r.canonicalTagName,
      severity: r.severity,
      kind: r.thresholdKind,
      value: r.value,
    }));
    const engineeringEnvelope = {
      max_pressure: envelope.maxPressure,
      max_flow_rate: envelope.maxFlowRate,
      max_temperature: envelope.maxTemperature,
      max_vibration: envelope.maxVibration,
      max_differential_pressure: envelope.maxDifferentialPressure,
      max_volume: envelope.maxVolume,
      max_gas_rate: envelope.maxGasRate,
      engineering_unit_set: ENGINEERING_UNIT_SET,
    };
    const ruleVersions = unitAlarmRules.map((r) => ({
      canonical_tag: r.canonicalTagName,
      severity: r.severity,
      version: 1,
    }));
    snapshot = await prisma.commissioningSnapshot.create({
      data: {
        tenantId,
        jobId: job.id,
        unitId,
        takenAt: SEED_DATE,
        effectiveThresholds: effectiveThresholds satisfies Prisma.InputJsonValue,
        sensorMappings: sensorMappings satisfies Prisma.InputJsonValue,
        engineeringEnvelope: engineeringEnvelope satisfies Prisma.InputJsonValue,
        ruleVersions: ruleVersions satisfies Prisma.InputJsonValue,
        immutable: true,
      },
    });
    record('created', 'commissioning_snapshot');

    // Close the circular FK: point the job at the freshly-created snapshot.
    await prisma.job.update({
      where: { id: job.id },
      data: { commissioningSnapshotId: snapshot.id },
    });
  } else {
    record('reused', 'commissioning_snapshot');
  }

  log(
    `well + job + snapshot present for ${unitCode}: well="${well.name}", job=${job.id}, snapshot=${snapshot.id}.`,
  );
  return { well, job, snapshot };
}

async function seedIntegrationPlaceholders(
  tenantId: string,
  unitId: string,
  sensors: SeededSensor[],
  canonicalTags: Map<string, { id: string }>,
): Promise<void> {
  // IntegrationSource: lookup by (tenantId, kind, name).
  const sourceName = 'Manual Reference Input';
  let source = await prisma.integrationSource.findFirst({
    where: { tenantId, kind: 'manual', name: sourceName },
  });
  if (source) {
    record('reused', 'integration_source');
  } else {
    source = await prisma.integrationSource.create({
      data: {
        tenantId,
        kind: 'manual',
        name: sourceName,
        status: 'inactive',
        // config defaults to {}::jsonb in the DB; explicit empty object is equivalent.
        config: {} satisfies Prisma.InputJsonValue,
        credentialsReference: null,
      },
    });
    record('created', 'integration_source');
  }

  // IntegrationMapping placeholder: map "ref-mapping-hp-pit-001" → HP-PIT-001 / p_inlet.
  // unique on (integration_source_id, external_identifier), so upsert is safe.
  const refSensor = sensors.find((s) => s.instrumentTag === 'HP-PIT-001');
  const refTag = canonicalTags.get('p_inlet');
  if (refSensor && refTag) {
    await prisma.integrationMapping.upsert({
      where: {
        integrationSourceId_externalIdentifier: {
          integrationSourceId: source.id,
          externalIdentifier: 'ref-mapping-hp-pit-001',
        },
      },
      update: {
        unitId,
        sensorId: refSensor.id,
        canonicalTagId: refTag.id,
        enabled: false,
        engineeringUnitOverride: 'psi',
        transformationReference: 'F4.3 placeholder mapping',
      },
      create: {
        tenantId,
        integrationSourceId: source.id,
        externalIdentifier: 'ref-mapping-hp-pit-001',
        unitId,
        sensorId: refSensor.id,
        canonicalTagId: refTag.id,
        engineeringUnitOverride: 'psi',
        transformationReference: 'F4.3 placeholder mapping',
        enabled: false,
      },
    });
    record('created', 'integration_mapping:upserted_x1');
  }
  log(`integration placeholders present: source="${sourceName}" (inactive), 1 disabled mapping.`);
}

async function seedAuditLog(
  tenantId: string,
  actorId: string,
  summary: Prisma.InputJsonValue,
): Promise<void> {
  const existing = await prisma.auditLog.findFirst({
    where: {
      tenantId,
      correlationId: SEED_CORRELATION_ID,
      action: 'created',
      entityType: 'reference_data',
    },
  });
  if (existing) {
    record('reused', 'audit_log');
    return;
  }
  await prisma.auditLog.create({
    data: {
      tenantId,
      actorId,
      action: 'created',
      entityType: 'reference_data',
      entityId: tenantId, // self-reference: the seed is scoped to the tenant.
      before: Prisma.JsonNull,
      after: summary,
      correlationId: SEED_CORRELATION_ID,
      ipAddress: null,
      userAgent: 'rvf-malinois-seed/f4.3',
      at: SEED_DATE,
    },
  });
  record('created', 'audit_log');
  log(`audit log written (correlation_id=${SEED_CORRELATION_ID}).`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  log('start.');

  const tenant = await seedTenant();
  const { systemUser, adminUser } = await seedUsers(tenant.id);
  const equipmentTypes = await seedEquipmentTypes();
  const canonicalTags = await seedCanonicalTags();
  const units = await seedMeasurementUnits(tenant.id, equipmentTypes);
  const sensors = await seedSensorsAndTransmitters(tenant.id, units);
  await seedSensorTagBindings(tenant.id, sensors, canonicalTags);
  await seedUnitConfigurations(tenant.id, units, sensors, systemUser.id);
  await seedUnitOperatingEnvelopes(tenant.id, units, systemUser.id);
  await seedAlarmRules(tenant.id, units, canonicalTags, systemUser.id);

  // Well + Job + CommissioningSnapshot anchored on HP-001 (single reference job).
  const hp001 = units.get('HP-001');
  if (!hp001) throw new Error('HP-001 missing after seedMeasurementUnits');
  const hp001Sensors = sensors.filter((s) => s.unitCode === 'HP-001');
  const wjs = await seedWellJobSnapshot(
    tenant.id,
    hp001.id,
    hp001.code,
    hp001Sensors,
    HP001_ALARM_RULES,
    HP001_ENVELOPE,
    adminUser.id,
  );

  await seedIntegrationPlaceholders(tenant.id, hp001.id, sensors, canonicalTags);

  const summary: Prisma.InputJsonValue = {
    seed_phase: 'F4.3',
    seed_correlation_id: SEED_CORRELATION_ID,
    tenant: { id: tenant.id, name: tenant.name },
    users: [systemUser.displayName, adminUser.displayName],
    equipment_types: Array.from(equipmentTypes.keys()),
    canonical_tags_count: canonicalTags.size,
    measurement_units: Array.from(units.keys()),
    sensors_count: sensors.length,
    well: { id: wjs.well.id, name: wjs.well.name },
    job_id: wjs.job.id,
    commissioning_snapshot_id: wjs.snapshot?.id ?? null,
    counters: {
      created: { ...counters.created },
      reused: { ...counters.reused },
    },
  };
  await seedAuditLog(tenant.id, systemUser.id, summary);

  log('completed.');
  log(`created counters: ${JSON.stringify(counters.created)}`);
  log(`reused counters:  ${JSON.stringify(counters.reused)}`);
}

main()
  .catch((err: unknown) => {
    log(`failed: ${err instanceof Error ? err.message : String(err)}`);
    if (err instanceof Error && err.stack) {
      console.error(err.stack);
    }
    process.exitCode = 1;
  })
  .finally(() => {
    void prisma.$disconnect();
  });
