import { cn } from '@rvf/ui';
import { CheckCircle2, FileText } from 'lucide-react';

import {
  formatDuration,
  formatKb,
  kindLabel,
  type ReportRecord,
  type ReportState,
} from './data/reports.mock';
import { KIND_DOT } from './ReportKindChip';

import { Panel } from '@/components/shell/Panel';

/**
 * ReportDetailPreview — audit-style preview of the selected report.
 *
 * Sits below the archive table. Reads as a document preview, not a
 * dashboard widget: three banded metadata grids on the left, the
 * "Included Sections" list on the right, every field label-over-value
 * with tabular-nums.
 *
 * Tone is calm. No charts, no decoration, no animation — this is the
 * audit handoff card.
 */
export interface ReportDetailPreviewProps {
  report: ReportRecord;
}

const STATE_STYLE: Record<ReportState, { dot: string; text: string; label: string }> = {
  QUEUED: { dot: 'bg-status-stale', text: 'text-status-stale', label: 'Queued' },
  GENERATING: { dot: 'bg-status-warn', text: 'text-status-warn', label: 'Generating' },
  READY: { dot: 'bg-status-info', text: 'text-status-info', label: 'Ready' },
  PENDING_APPROVAL: { dot: 'bg-status-warn', text: 'text-status-warn', label: 'Pending Approval' },
  DELIVERED: { dot: 'bg-status-normal', text: 'text-status-normal', label: 'Delivered' },
  FAILED: { dot: 'bg-status-alarm', text: 'text-status-alarm', label: 'Failed' },
};

export const ReportDetailPreview = ({ report }: ReportDetailPreviewProps) => {
  const ss = STATE_STYLE[report.state];

  return (
    <Panel
      title="Report Detail Preview"
      density="compact"
      meta={
        <span
          className={cn(
            'inline-flex items-center gap-1.5 px-2 py-0.5 rounded-xs font-semibold uppercase tracking-micro',
            ss.text,
          )}
        >
          <span
            aria-hidden="true"
            className={cn('inline-block w-1.5 h-1.5 rounded-full', ss.dot)}
          />
          {ss.label}
        </span>
      }
    >
      <header className="flex items-baseline gap-3 flex-wrap">
        <span className="font-mono text-base font-bold uppercase tracking-wide text-text-primary leading-none">
          {report.id}
        </span>
        <span className="inline-flex items-center gap-1.5 text-micro uppercase tracking-micro text-text-secondary">
          <span
            aria-hidden="true"
            className={cn('inline-block w-1.5 h-1.5 rounded-full', KIND_DOT[report.kind])}
          />
          {kindLabel(report.kind)}
        </span>
        {report.well ? (
          <span className="text-micro uppercase tracking-micro text-text-muted">
            · <span className="font-mono">{report.well}</span> · {report.unit}
          </span>
        ) : (
          <span className="text-micro uppercase tracking-micro text-text-muted">
            · {report.unit}
          </span>
        )}
      </header>

      {/* Two-column body: left = metadata grids, right = sections. */}
      <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_minmax(0,260px)] gap-3.5">
        <dl className="flex flex-col text-xs">
          {/* Band 1 — provenance */}
          <div className="grid grid-cols-4 gap-x-3 gap-y-3 pb-3.5 border-b border-border-subtle">
            <Field label="Report ID" value={report.id} mono />
            <Field label="Kind" value={kindLabel(report.kind)} />
            <Field label="Well" value={report.well ?? '—'} mono />
            <Field label="Unit" value={report.unit} />
            <Field label="Job" value={report.job ?? '—'} mono />
            <Field label="Generated" value={report.generatedAt} mono />
            <Field label="Generated By" value={report.generatedBy} mono />
            <Field
              label="Approved By"
              value={report.approvedBy ?? 'Pending'}
              tone={report.approvedBy ? 'text-text-primary' : 'text-status-warn'}
              mono
            />
          </div>

          {/* Band 2 — operational summary */}
          <div className="grid grid-cols-4 gap-x-3 gap-y-3 py-3.5 border-b border-border-subtle">
            <Field label="Run Duration" value={formatDuration(report.durationSec)} mono />
            <Field
              label="Alarms"
              value={report.alarmCount.toString()}
              tone={
                report.alarmCount >= 25
                  ? 'text-status-alarm'
                  : report.alarmCount >= 10
                    ? 'text-status-warn'
                    : 'text-text-primary'
              }
              mono
            />
            <Field
              label="Avg Pressure"
              value={
                report.avgPressurePsi === 0
                  ? '—'
                  : `${report.avgPressurePsi.toLocaleString('en-US')} psi`
              }
              mono
            />
            <Field
              label="Avg Water Cut"
              value={report.avgWaterCutPct === 0 ? '—' : `${report.avgWaterCutPct.toFixed(1)} %`}
              mono
            />
          </div>

          {/* Band 3 — file */}
          <div className="grid grid-cols-4 gap-x-3 gap-y-3 pt-3.5">
            <Field label="File Size" value={formatKb(report.sizeKb)} mono />
            <Field label="Sections" value={report.sections.length.toString()} mono />
            <Field label="State" value={ss.label} tone={ss.text} />
            <Field label="Audit" value={report.approvedBy ? 'Sealed' : 'Open'} />
          </div>
        </dl>

        {/* Right column — included sections (the "document table of
            contents" view). */}
        <section
          aria-label="Included sections"
          className="flex flex-col gap-2 bg-surface-raised border border-border-subtle rounded-xs p-3.5"
        >
          <header className="flex items-center justify-between">
            <h3 className="inline-flex items-center gap-1.5 text-micro uppercase tracking-wide font-bold text-text-primary">
              <FileText className="w-3.5 h-3.5 text-text-secondary" aria-hidden="true" />
              Included Sections
            </h3>
            <span className="font-mono text-micro uppercase tracking-micro text-text-muted">
              {report.sections.length}
            </span>
          </header>
          {report.sections.length === 0 ? (
            <p className="text-xs text-text-muted">
              No sections were rendered — generation failed before the document was assembled.
            </p>
          ) : (
            <ol className="flex flex-col">
              {report.sections.map((s, i) => (
                <li
                  key={s}
                  className="flex items-center justify-between gap-2 py-2 border-b border-border-subtle last:border-b-0"
                >
                  <span className="flex items-center gap-2 min-w-0">
                    <span className="font-mono tabular-nums text-micro uppercase tracking-micro text-text-muted shrink-0">
                      §{String(i + 1).padStart(2, '0')}
                    </span>
                    <span className="text-xs text-text-primary truncate">{s}</span>
                  </span>
                  <CheckCircle2
                    className="w-3.5 h-3.5 text-status-normal shrink-0 opacity-80"
                    aria-hidden="true"
                  />
                </li>
              ))}
            </ol>
          )}
        </section>
      </div>
    </Panel>
  );
};

const Field = ({
  label,
  value,
  tone,
  mono = false,
}: {
  label: string;
  value: string;
  tone?: string;
  mono?: boolean;
}) => (
  <div className="flex flex-col gap-1 min-w-0">
    <dt className="text-micro uppercase tracking-micro text-text-muted leading-none">{label}</dt>
    <dd
      className={cn(
        'truncate font-semibold leading-none',
        mono ? 'font-mono tabular-nums' : 'uppercase tracking-micro',
        tone ?? 'text-text-primary',
      )}
    >
      {value}
    </dd>
  </div>
);
