/**
 * Mock sensors — F3 seed.
 *
 * Each sensor has a `unitId` pointing at one row in `mockUnits`. The
 * adapter's `getSensorsByUnitId()` relies on that link; route handlers
 * reject any telemetry whose sensor.unitId doesn't match the payload.
 */
import type { Sensor } from '@/types/api';

const ISO_2026_05_24 = '2026-05-24T00:00:00.000Z';

export const MOCK_SENSORS: readonly Sensor[] = [
  // ---- unit-hp-001 ------------------------------------------------------
  {
    id: 'sensor-pressure-inlet-hp-001',
    unitId: 'unit-hp-001',
    tag: 'PT-001',
    name: 'Inlet Pressure HP',
    type: 'pressure',
    measurement: 'Inlet pressure',
    unit: 'psi',
    status: 'online',
    minRange: 0,
    maxRange: 6000,
    currentValue: 3250,
    lastReadingAt: ISO_2026_05_24,
    createdAt: ISO_2026_05_24,
    updatedAt: ISO_2026_05_24,
  },
  {
    id: 'sensor-pressure-separator-hp-001',
    unitId: 'unit-hp-001',
    tag: 'PT-002',
    name: 'Separator Pressure HP',
    type: 'pressure',
    measurement: 'Separator pressure',
    unit: 'psi',
    status: 'online',
    minRange: 0,
    maxRange: 5000,
    currentValue: 2850,
    lastReadingAt: ISO_2026_05_24,
    createdAt: ISO_2026_05_24,
    updatedAt: ISO_2026_05_24,
  },
  {
    id: 'sensor-temperature-inlet-hp-001',
    unitId: 'unit-hp-001',
    tag: 'TT-001',
    name: 'Inlet Temperature HP',
    type: 'temperature',
    measurement: 'Inlet temperature',
    unit: 'degC',
    status: 'online',
    minRange: -20,
    maxRange: 150,
    currentValue: 78,
    lastReadingAt: ISO_2026_05_24,
    createdAt: ISO_2026_05_24,
    updatedAt: ISO_2026_05_24,
  },
  {
    id: 'sensor-flow-main-hp-001',
    unitId: 'unit-hp-001',
    tag: 'FT-001',
    name: 'Main Flow HP',
    type: 'flow',
    measurement: 'Main flow rate',
    unit: 'bpd',
    status: 'online',
    minRange: 0,
    maxRange: 4000,
    currentValue: 1850,
    lastReadingAt: ISO_2026_05_24,
    createdAt: ISO_2026_05_24,
    updatedAt: ISO_2026_05_24,
  },

  // ---- unit-mp-001 ------------------------------------------------------
  {
    id: 'sensor-pressure-inlet-mp-001',
    unitId: 'unit-mp-001',
    tag: 'PT-101',
    name: 'Inlet Pressure MP',
    type: 'pressure',
    measurement: 'Inlet pressure',
    unit: 'psi',
    status: 'online',
    minRange: 0,
    maxRange: 2500,
    currentValue: 1400,
    lastReadingAt: ISO_2026_05_24,
    createdAt: ISO_2026_05_24,
    updatedAt: ISO_2026_05_24,
  },
  {
    id: 'sensor-temperature-inlet-mp-001',
    unitId: 'unit-mp-001',
    tag: 'TT-101',
    name: 'Inlet Temperature MP',
    type: 'temperature',
    measurement: 'Inlet temperature',
    unit: 'degC',
    status: 'online',
    minRange: -20,
    maxRange: 120,
    currentValue: 62,
    lastReadingAt: ISO_2026_05_24,
    createdAt: ISO_2026_05_24,
    updatedAt: ISO_2026_05_24,
  },
  {
    id: 'sensor-flow-main-mp-001',
    unitId: 'unit-mp-001',
    tag: 'FT-101',
    name: 'Main Flow MP',
    type: 'flow',
    measurement: 'Main flow rate',
    unit: 'bpd',
    status: 'online',
    minRange: 0,
    maxRange: 2000,
    currentValue: 980,
    lastReadingAt: ISO_2026_05_24,
    createdAt: ISO_2026_05_24,
    updatedAt: ISO_2026_05_24,
  },

  // ---- unit-lp-001 ------------------------------------------------------
  {
    id: 'sensor-pressure-inlet-lp-001',
    unitId: 'unit-lp-001',
    tag: 'PT-201',
    name: 'Inlet Pressure LP',
    type: 'pressure',
    measurement: 'Inlet pressure',
    unit: 'psi',
    status: 'offline',
    minRange: 0,
    maxRange: 1000,
    currentValue: null,
    lastReadingAt: null,
    createdAt: ISO_2026_05_24,
    updatedAt: ISO_2026_05_24,
  },
  {
    id: 'sensor-temperature-inlet-lp-001',
    unitId: 'unit-lp-001',
    tag: 'TT-201',
    name: 'Inlet Temperature LP',
    type: 'temperature',
    measurement: 'Inlet temperature',
    unit: 'degC',
    status: 'online',
    minRange: -20,
    maxRange: 90,
    currentValue: 45,
    lastReadingAt: ISO_2026_05_24,
    createdAt: ISO_2026_05_24,
    updatedAt: ISO_2026_05_24,
  },
  {
    id: 'sensor-flow-main-lp-001',
    unitId: 'unit-lp-001',
    tag: 'FT-201',
    name: 'Main Flow LP',
    type: 'flow',
    measurement: 'Main flow rate',
    unit: 'bpd',
    status: 'online',
    minRange: 0,
    maxRange: 600,
    currentValue: 240,
    lastReadingAt: ISO_2026_05_24,
    createdAt: ISO_2026_05_24,
    updatedAt: ISO_2026_05_24,
  },
];
